refactor

diff --git a/git-get b/git-get
--- a/git-get
+++ b/git-get
@@ -263,31 +263,24 @@ _checkout() {
     # Destination directorys is where you download the repo files.
     # Destination directory will be tmp during dry run and compress.
     # Working directory is where we want to place the compressed archives
-    : ${1? ERROR Function: ${FUNCNAME[0]}() Usage: " ${FUNCNAME[0]} file_name"}
-    local file_name="${1}"
 
-    cd "${DEST_DIR_PATH}" 2>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to change directory to ${DEST_DIR_PATH}"
 
-    [ "$WORKING_DIR_PATH" != "$(pwd)" ] || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}()  Refusing to delete wrong .git directory, exiting" # this means you were about delete the .git of the main directory
     echo_verbose "Checking out $BRANCH..." 2
     ! EXPORT_ON && ( git checkout -q "${BRANCH}" || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting")
-   EXPORT_ON && echo_verbose "-x:Using git archive command to export..." 1
-   EXPORT_ON && (git archive -o latest.tar.gz HEAD 1>/dev/null  && tar -xzvf latest.tar.gz  1>/dev/null && rm latest.tar.gz  1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() export failed, exiting...")
 
 
 
 
+}
 
-    echo_verbose "Updating submodules..." 2
 
-    git submodule update -q --init --recursive || die "ERROR: ${FUNCNAME[0]}() Failed to update git submodules, exiting"
-    echo_verbose "Removing git directory" 2
+_compress(){
+   : ${1? ERROR Function: ${FUNCNAME[0]}() Usage: " ${FUNCNAME[0]} file_name"}
 
-    # remove .git directory unless we tell it not to with the -k option
-    KEEP_REPO_ON && echo_verbose "-k: Keeping .git repository files ..." 1 || echo_verbose "-k:removing .git repository files.." 1
-    KEEP_REPO_ON ||  find $PWD -maxdepth 1 -name ".git" -type d -exec rm -rf {} \;  # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
-    KEEP_REPO_ON || ([ -d .git ] && die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to remove .git, exiting")
-    COMPRESS_ON && echo_verbose "Compressing directories using ${COMPRESS_TYPE}" 2
+        local file_name="${DEST_DIR_NAME}"-"${BRANCH}"
+
+    COMPRESS_ON &&  echo_verbose "Compressing files..." 1
+    COMPRESS_ON && echo_verbose "Compressing files  using ${COMPRESS_TYPE}" 2
 
     ZIP_ON && echo_verbose "Zip command: zip $WORKING_DIR_PATH/${file_name}.zip $PWD" 3
     ZIP_ON && (zip "$WORKING_DIR_PATH"/"${file_name}".zip $PWD 1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to zip, exiting")
@@ -295,36 +288,100 @@ _checkout() {
     TAR_ON && echo_verbose "Tar Command: tar -zcvf $WORKING_DIR_PATH/${file_name}.tar.gz -C $(dirname ${DEST_DIR_PATH}) ${DEST_DIR_NAME}" 3
     TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz -C $(dirname ${DEST_DIR_PATH}) "${DEST_DIR_NAME}" 1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to tar, exiting")
 
-    cd - 1>/dev/null
+
+(COMPRESS_ON || DRY_RUN_ON) && echo_verbose "Deleting temporary files..." 3  && saferRmdir "${DEST_DIR_PATH}"
+
+}
+
+_export(){
+
+
+   EXPORT_ON && echo_verbose "-x:Using git archive command to export..." 1
+   EXPORT_ON && (git archive -o latest.tar.gz HEAD 1>/dev/null  && tar -xzvf latest.tar.gz  1>/dev/null && rm latest.tar.gz  1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() export failed, exiting...")
+
+
+}
+
+_update_submodules(){
+
+    echo_verbose "Updating submodules..." 2
+
+    git submodule update -q --init --recursive || die "ERROR: ${FUNCNAME[0]}() Failed to update git submodules, exiting"
 
 }
 
 
+_rm_git(){
+
+    echo_verbose "Removing git directory" 2
+
+    [ "$WORKING_DIR_PATH" != "$(pwd)" ] || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}()  Refusing to delete wrong .git directory, exiting" # this means you were about delete the .git of the main directory
+
+
+    # remove .git directory unless we tell it not to with the -k option
+    KEEP_REPO_ON && echo_verbose "-k: Keeping .git repository files ..." 1 || echo_verbose "-k:removing .git repository files.." 1
+    KEEP_REPO_ON ||  find $PWD -maxdepth 1 -name ".git" -type d -exec rm -rf {} \;  # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
+    KEEP_REPO_ON || ([ -d .git ] && die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to remove .git, exiting")
+
+
+}
 
 echo_verbose() {
 
     (( $2 <= $_arg_verbose )) && echo "${1}"
 
 }
-get() {
 
-    local file_name="${DEST_DIR_NAME}"-"${BRANCH}"
+show_download_message(){
 
-    local cmd_options='--depth=1 --branch='"${BRANCH}"' '"${REPO_PATH}"' '"${DEST_DIR_PATH}"
-
-    # remove the target directory if compressed or dry_run since its in temp and will block if it already exists
-    (COMPRESS_ON || DRY_RUN_ON) && saferRmdir "${DEST_DIR_PATH}"
-    TAR_ON || ZIP_ON && echo_verbose "downloading $COMPRESS_TYPE of repo $REPO_PATH ...." 0
-
-
+    COMPRESS_ON && ( echo_verbose "downloading $COMPRESS_TYPE of branch ${BRANCH} from repo "${REPO_PATH}"...." 0)
+    ! COMPRESS_ON && ( echo_verbose "downloading  branch ${BRANCH} from repo "${REPO_PATH}"..." 0)
     echo_verbose "Cloning repository..." 1
 
-    (DRY_RUN_ON || VERBOSE_ON) && echo_verbose "using clone command: git clone --no-checkout ${cmd_options}" 3
+}
 
-    git clone -q --no-checkout ${cmd_options} 1>/dev/null || die "Error: Failed git clone"
-    COMPRESS_ON &&  echo_verbose "Compressing files..." 1
-    _checkout "${file_name}"
+_git_clone(){
 
+     local cmd_options='--depth=1 --branch='"${BRANCH}"' '"${REPO_PATH}"' '"${DEST_DIR_PATH}"
+
+   VERBOSE_ON && echo_verbose "using clone command: git clone --no-checkout ${cmd_options}" 3
+    git clone -q --no-checkout "${cmd_options}" 1>/dev/null || die "Error: Failed git clone"
+
+}
+
+get() {
+
+
+
+
+
+    # remove the target directory if compressed or dry_run since its in temp and will block if it already exists
+
+    show_downloading_message
+
+
+    _git_clone
+
+   cd "${DEST_DIR_PATH}" 1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to change directory to ${DEST_DIR_PATH}"
+
+
+    _checkout
+
+
+
+
+_export
+
+_update_submodules
+
+
+
+_rm_git
+_compress
+
+
+
+    cd - 1>/dev/null
 
 
    # NOT NEEDED:  COMPRESS_ON && EXPORT_ON && _export "${file_name}" # compress respecting .gitattributes
