reformat

diff --git a/git-get b/git-get
--- a/git-get
+++ b/git-get
@@ -49,7 +49,7 @@ esac
 #####################
 
 # Argbash Parser
-source "$( dirname "${BASH_SOURCE[0]}" )/git-get-parser.sh"
+source "$(dirname "${BASH_SOURCE[0]}")/git-get-parser.sh"
 getRepoPath() {
 
     echo "${_arg_repository}"
@@ -264,22 +264,17 @@ _checkout() {
     # Destination directory will be tmp during dry run and compress.
     # Working directory is where we want to place the compressed archives
 
-
     echo_verbose "Checking out $BRANCH..." 2
-    ! EXPORT_ON && ( git checkout -q "${BRANCH}" || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting")
-
-
-
+    ! EXPORT_ON && (git checkout -q "${BRANCH}" || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting")
 
 }
 
+_compress() {
+    : ${1? ERROR Function: ${FUNCNAME[0]}() Usage: " ${FUNCNAME[0]} file_name"}
 
-_compress(){
-   : ${1? ERROR Function: ${FUNCNAME[0]}() Usage: " ${FUNCNAME[0]} file_name"}
+    local file_name="${DEST_DIR_NAME}"-"${BRANCH}"
 
-        local file_name="${DEST_DIR_NAME}"-"${BRANCH}"
-
-    COMPRESS_ON &&  echo_verbose "Compressing files..." 1
+    COMPRESS_ON && echo_verbose "Compressing files..." 1
     COMPRESS_ON && echo_verbose "Compressing files  using ${COMPRESS_TYPE}" 2
 
     ZIP_ON && echo_verbose "Zip command: zip $WORKING_DIR_PATH/${file_name}.zip $PWD" 3
@@ -288,21 +283,18 @@ _compress(){
     TAR_ON && echo_verbose "Tar Command: tar -zcvf $WORKING_DIR_PATH/${file_name}.tar.gz -C $(dirname ${DEST_DIR_PATH}) ${DEST_DIR_NAME}" 3
     TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz -C $(dirname ${DEST_DIR_PATH}) "${DEST_DIR_NAME}" 1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to tar, exiting")
 
-
-(COMPRESS_ON || DRY_RUN_ON) && echo_verbose "Deleting temporary files..." 3  && saferRmdir "${DEST_DIR_PATH}"
-
-}
-
-_export(){
-
-
-   EXPORT_ON && echo_verbose "-x:Using git archive command to export..." 1
-   EXPORT_ON && (git archive -o latest.tar.gz HEAD 1>/dev/null  && tar -xzvf latest.tar.gz  1>/dev/null && rm latest.tar.gz  1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() export failed, exiting...")
-
+    (COMPRESS_ON || DRY_RUN_ON) && echo_verbose "Deleting temporary files..." 3 && saferRmdir "${DEST_DIR_PATH}"
 
 }
 
-_update_submodules(){
+_export() {
+
+    EXPORT_ON && echo_verbose "-x:Using git archive command to export..." 1
+    EXPORT_ON && (git archive -o latest.tar.gz HEAD 1>/dev/null && tar -xzvf latest.tar.gz 1>/dev/null && rm latest.tar.gz 1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() export failed, exiting...")
+
+}
+
+_update_submodules() {
 
     echo_verbose "Updating submodules..." 2
 
@@ -310,81 +302,64 @@ _update_submodules(){
 
 }
 
-
-_rm_git(){
+_rm_git() {
 
     echo_verbose "Removing git directory" 2
 
     [ "$WORKING_DIR_PATH" != "$(pwd)" ] || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}()  Refusing to delete wrong .git directory, exiting" # this means you were about delete the .git of the main directory
 
-
     # remove .git directory unless we tell it not to with the -k option
     KEEP_REPO_ON && echo_verbose "-k: Keeping .git repository files ..." 1 || echo_verbose "-k:removing .git repository files.." 1
-    KEEP_REPO_ON ||  find $PWD -maxdepth 1 -name ".git" -type d -exec rm -rf {} \;  # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
+    KEEP_REPO_ON || find $PWD -maxdepth 1 -name ".git" -type d -exec rm -rf {} \; # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
     KEEP_REPO_ON || ([ -d .git ] && die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to remove .git, exiting")
-
 
 }
 
 echo_verbose() {
 
-    (( $2 <= $_arg_verbose )) && echo "${1}"
+    (($2 <= $_arg_verbose)) && echo "${1}"
 
 }
 
-show_download_message(){
+show_download_message() {
 
-    COMPRESS_ON && ( echo_verbose "downloading $COMPRESS_TYPE of branch ${BRANCH} from repo "${REPO_PATH}"...." 0)
-    ! COMPRESS_ON && ( echo_verbose "downloading  branch ${BRANCH} from repo "${REPO_PATH}"..." 0)
+    COMPRESS_ON && (echo_verbose "downloading $COMPRESS_TYPE of branch ${BRANCH} from repo "${REPO_PATH}"...." 0)
+    ! COMPRESS_ON && (echo_verbose "downloading  branch ${BRANCH} from repo "${REPO_PATH}"..." 0)
     echo_verbose "Cloning repository..." 1
 
 }
 
-_git_clone(){
+_git_clone() {
 
-     local cmd_options='--depth=1 --branch='"${BRANCH}"' '"${REPO_PATH}"' '"${DEST_DIR_PATH}"
+    local cmd_options='--depth=1 --branch='"${BRANCH}"' '"${REPO_PATH}"' '"${DEST_DIR_PATH}"
 
-   VERBOSE_ON && echo_verbose "using clone command: git clone --no-checkout ${cmd_options}" 3
+    VERBOSE_ON && echo_verbose "using clone command: git clone --no-checkout ${cmd_options}" 3
     git clone -q --no-checkout "${cmd_options}" 1>/dev/null || die "Error: Failed git clone"
 
 }
 
 get() {
 
-
-
-
-
     # remove the target directory if compressed or dry_run since its in temp and will block if it already exists
 
     show_downloading_message
 
-
     _git_clone
 
-   cd "${DEST_DIR_PATH}" 1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to change directory to ${DEST_DIR_PATH}"
-
+    cd "${DEST_DIR_PATH}" 1>/dev/null || die "ERROR: line ${LINENO} ,${FUNCNAME[0]}() Failed to change directory to ${DEST_DIR_PATH}"
 
     _checkout
 
+    _export
 
+    _update_submodules
 
-
-_export
-
-_update_submodules
-
-
-
-_rm_git
-_compress
-
-
+    _rm_git
+    _compress
 
     cd - 1>/dev/null
 
-
-   # NOT NEEDED:  COMPRESS_ON && EXPORT_ON && _export "${file_name}" # compress respecting .gitattributes
+    # NOT NEEDED:  COMPRESS_ON && EXPORT_ON && _export "${file_name}" # compress respecting .gitattributes
 
 }
 
