added export

diff --git a/git-get b/git-get
--- a/git-get
+++ b/git-get
@@ -266,74 +266,43 @@ _compress() {
     : ${1? ERROR Function: ${FUNCNAME[0]}() Usage: " ${FUNCNAME[0]} file_name"}
     local file_name="${1}"
 
-    cd "${DEST_DIR_PATH}" 2>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to change directory to ${DEST_DIR_PATH}"
+    cd "${DEST_DIR_PATH}" 2>/dev/null || die "ERROR: ${LINENO} ${FUNCNAME[0]}() Failed to change directory to ${DEST_DIR_PATH}"
 
-    [ "$WORKING_DIR_PATH" != "$(pwd)" ] || die "${FUNCNAME[0]}()  Refusing to delete wrong .git directory, exiting" # this means you were about delete the .git of the main directory
+    [ "$WORKING_DIR_PATH" != "$(pwd)" ] || die "ERROR: ${LINENO} ${FUNCNAME[0]}()  Refusing to delete wrong .git directory, exiting" # this means you were about delete the .git of the main directory
     echo_verbose "Checking out $BRANCH..." 2
-    git checkout -q "${BRANCH}" || die "ERROR: ${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting"
+    ! EXPORT_ON && ( git checkout -q "${BRANCH}" || die "ERROR: ${LINENO} ${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting")
+   EXPORT_ON && echo_verbose "-x:Using git archive command to export..." 1
+   (EXPORT_ON && git archive -o latest.tar.gz HEAD 1>/dev/null  && tar -xzvf latest.tar.gz 1>/dev/null && rm latest.tar.gz  ) || die "ERROR: ${LINENO} ${FUNCNAME[0]}() export failed, exiting..."
+
+
+
+
+
     echo_verbose "Updating submodules..." 2
 
     git submodule update -q --init --recursive || die "ERROR: ${FUNCNAME[0]}() Failed to update git submodules, exiting"
     echo_verbose "Removing git directory" 2
 
     # remove .git directory unless we tell it not to with the -k option
+    KEEP_REPO_ON && echo_verbose "-k: Keeping .git repository files ..." 1 || echo_verbose "-k:removing .git repository files.." 1
     KEEP_REPO_ON || find $PWD -name ".git" -type d -exec rm -rf {} \; 2>/dev/null # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
-    KEEP_REPO_ON || [ -d .git ] && die "ERROR: ${FUNCNAME[0]}() Failed to remove .git, exiting"
+    KEEP_REPO_ON || ([ -d .git ] && die "ERROR: ${LINENO} ${FUNCNAME[0]}() Failed to remove .git, exiting")
     echo_verbose "Compressing directories using ${COMPRESS_TYPE}" 2
 
     ZIP_ON && echo_verbose "Zip command: zip $WORKING_DIR_PATH/${file_name}.zip $PWD" 3
-    ZIP_ON && (zip "$WORKING_DIR_PATH"/"${file_name}".zip $PWD 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to zip, exiting")
+    ZIP_ON && (zip "$WORKING_DIR_PATH"/"${file_name}".zip $PWD 1>/dev/null || die "ERROR: ${LINENO} ${FUNCNAME[0]}() Failed to zip, exiting")
 
-    TAR_ON && echo_verbose "Tar Command: tar -zcvf $WORKING_DIR_PATH"/"${file_name}".tar.gz -C $(dirname ${DEST_DIR_PATH}) "${DEST_DIR_NAME}" 3
-    TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz -C $(dirname ${DEST_DIR_PATH}) "${DEST_DIR_NAME}" 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to tar, exiting")
-
-    cd - 1>/dev/null
-
-}
-
-rmGit() {
-    echo $(pwd)
-    ls -ail | grep .git
-    find . -name '.git' -type d -exec /bin/rm -rf {} \;
-
-}
-
-_exportDONTUSE() {
-
-    # Note the difference between Working Directory and Destination Directory.
-    # Working directory is where you started from, where you called the script from
-    # Destination directorys is where you download the repo files.
-    # Destination directory will be tmp during dry run and compress.
-    # Working directory is where we want to place the compressed archives
-    : ${1? ERROR Function: ${FUNCNAME[0]}() Usage: " ${FUNCNAME[0]} file_name"}
-    local file_name="${1}"
-
-    cd "${DEST_DIR_PATH}" 2>/dev/null || [ ! $? ] || die "ERROR: ${FUNCNAME[0]}() Failed to change directory to ${DEST_DIR_PATH}"
-
-    [ "$WORKING_DIR_PATH" != "$(pwd)" ] || die "${FUNCNAME[0]}()  Refusing to delete wrong .git directory, exiting" # this means you were about delete the .git of the main directory
-
-    # we don't checkout since we will be using git archive which respects export-ignore
-    # we then expand the archive
-    # git checkout "${BRANCH}" || [ ! $? ] || die "ERROR: ${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting"
-
-    git archive -o latest.tar.gz HEAD || die "ERROR: ${FUNCNAME[0]}() git archive failed, exiting..." ||
-        tar -xzvf latest.tar.gz || [ ! $? ] || die "ERROR: ${FUNCNAME[0]}() tar expansion failed,export is offo update git submodules, exiting"
-
-    # remove .git directory unless we tell it not to with the -k option
-    KEEP_REPO_ON || find $PWD -name ".git" -type d -exec rm -rf {} \; 2>/dev/null # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
-    KEEP_REPO_ON || [ -d .git ] && die "ERROR: ${FUNCNAME[0]}() Failed to remove .git, exiting"
-    COMPRESS_ON && echo "Compressing directories using $COMPRESS_TYPE"
-    ZIP_ON && (zip "$WORKING_DIR_PATH"/"${file_name}".zip . 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to zip, exiting")
-
-    TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz $PWD 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to tar, exiting")
+    TAR_ON && echo_verbose "Tar Command: tar -zcvf $WORKING_DIR_PATH/${file_name}.tar.gz -C $(dirname ${DEST_DIR_PATH}) ${DEST_DIR_NAME}" 3
+    TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz -C $(dirname ${DEST_DIR_PATH}) "${DEST_DIR_NAME}" 1>/dev/null || die "ERROR: ${LINENO} ${FUNCNAME[0]}() Failed to tar, exiting")
 
     cd - 1>/dev/null
 
 }
+
 
 echo_verbose() {
 
-    VERBOSE_ON && (( $2 <= $_arg_verbose )) && echo "${1}"
+    (( $2 <= $_arg_verbose )) && echo "${1}"
 
 }
 get() {
@@ -344,16 +313,18 @@ get() {
 
     # remove the target directory if compressed or dry_run since its in temp and will block if it already exists
     (COMPRESS_ON || DRY_RUN_ON) && saferRmdir "${DEST_DIR_PATH}"
+    TAR_ON || ZIP_ON && echo_verbose "downloading $COMPRESS_TYPE of repo $REPO_PATH ...." 0
+
 
     echo_verbose "Cloning repository..." 1
 
     (DRY_RUN_ON || VERBOSE_ON) && echo_verbose "using clone command: git clone --no-checkout ${cmd_options}" 3
 
-    git clone -q --no-checkout ${cmd_options} 1>/dev/null || die "Error: Failed git clone --no-checkout ${cmd_options}"
-    echo_verbose "Compressing files..." 1
-    COMPRESS_ON && ! EXPORT_ON && _compress "${file_name}" # compress ignoring .gitattributes
+    git clone -q --no-checkout ${cmd_options} 1>/dev/null || die "Error: Failed git clone"
+    COMPRESS_ON &&  echo_verbose "Compressing files..." 1
+    COMPRESS_ON && _compress "${file_name}" # compress ignoring .gitattributes
 
-    COMPRESS_ON && EXPORT_ON && _export "${file_name}" # compress respecting .gitattributes
+   # NOT NEEDED:  COMPRESS_ON && EXPORT_ON && _export "${file_name}" # compress respecting .gitattributes
 
 }
 
