bugfixes

diff --git a/git-get b/git-get
--- a/git-get
+++ b/git-get
@@ -118,7 +118,7 @@ getDestinationDirPath() {
     : ${1? ERROR Function: ${FUNCNAME[0]}() Usage: " ${FUNCNAME[0]} dir_name"}
 
     local dir_name="${1}"
-    local result="./${dir_name}"
+    local result="${WORKING_DIR_PATH}/${dir_name}"
     (DRY_RUN_ON || COMPRESS_ON) && result=$TEMP_DIR_PATH/$dir_name
 
     echo ${result}
@@ -270,22 +270,22 @@ _compress() {
 
     [ "$WORKING_DIR_PATH" != "$(pwd)" ] || die "${FUNCNAME[0]}()  Refusing to delete wrong .git directory, exiting" # this means you were about delete the .git of the main directory
     echo_verbose "Checking out $BRANCH..." 2
-    git checkout "${BRANCH}" || die "ERROR: ${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting"
+    git checkout -q "${BRANCH}" || die "ERROR: ${FUNCNAME[0]}() Failed to check out branch ${BRANCH}, exiting"
     echo_verbose "Updating submodules..." 2
 
-    git submodule update --init --recursive || die "ERROR: ${FUNCNAME[0]}() Failed to update git submodules, exiting"
+    git submodule update -q --init --recursive || die "ERROR: ${FUNCNAME[0]}() Failed to update git submodules, exiting"
     echo_verbose "Removing git directory" 2
 
     # remove .git directory unless we tell it not to with the -k option
-    # KEEP_REPO_ON || find $PWD -name ".git" -type d -exec rm -rf {} \; 2>/dev/null # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
-    #  KEEP_REPO_ON || [ -d .git ] && die "ERROR: ${FUNCNAME[0]}() Failed to remove .git, exiting"
+    KEEP_REPO_ON || find $PWD -name ".git" -type d -exec rm -rf {} \; 2>/dev/null # this will always return a $?=1 because of recursion, unless maxdepth=1 is used.
+    KEEP_REPO_ON || [ -d .git ] && die "ERROR: ${FUNCNAME[0]}() Failed to remove .git, exiting"
     echo_verbose "Compressing directories using ${COMPRESS_TYPE}" 2
 
     ZIP_ON && echo_verbose "Zip command: zip $WORKING_DIR_PATH/${file_name}.zip $PWD" 3
     ZIP_ON && (zip "$WORKING_DIR_PATH"/"${file_name}".zip $PWD 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to zip, exiting")
 
-    TAR_ON && echo_verbose "Tar command:  tar -zcvf $WORKING_DIR_PATH/${file_name}.tar.gz $PWD" 3
-    TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz $PWD 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to tar, exiting")
+    TAR_ON && echo_verbose "Tar Command: tar -zcvf $WORKING_DIR_PATH"/"${file_name}".tar.gz -C $(dirname ${DEST_DIR_PATH}) "${DEST_DIR_NAME}" 3
+    TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz -C $(dirname ${DEST_DIR_PATH}) "${DEST_DIR_NAME}" 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to tar, exiting")
 
     cd - 1>/dev/null
 
@@ -325,7 +325,7 @@ _exportDONTUSE() {
     COMPRESS_ON && echo "Compressing directories using $COMPRESS_TYPE"
     ZIP_ON && (zip "$WORKING_DIR_PATH"/"${file_name}".zip . 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to zip, exiting")
 
-    TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz . 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to tar, exiting")
+    TAR_ON && (tar -zcvf "$WORKING_DIR_PATH"/"${file_name}".tar.gz $PWD 1>/dev/null || die "ERROR: ${FUNCNAME[0]}() Failed to tar, exiting")
 
     cd - 1>/dev/null
 
@@ -333,7 +333,7 @@ _exportDONTUSE() {
 
 echo_verbose() {
 
-    VERBOSE_ON && [ $2 -le $_arg_verbose ] && echo "${1}"
+    VERBOSE_ON && (( $2 <= $_arg_verbose )) && echo "${1}"
 
 }
 get() {
@@ -345,8 +345,9 @@ get() {
     # remove the target directory if compressed or dry_run since its in temp and will block if it already exists
     (COMPRESS_ON || DRY_RUN_ON) && saferRmdir "${DEST_DIR_PATH}"
 
-    (DRY_RUN_ON || VERBOSE_ON) && echo "using clone command: git clone --no-checkout ${cmd_options}"
     echo_verbose "Cloning repository..." 1
+
+    (DRY_RUN_ON || VERBOSE_ON) && echo_verbose "using clone command: git clone --no-checkout ${cmd_options}" 3
 
     git clone -q --no-checkout ${cmd_options} 1>/dev/null || die "Error: Failed git clone --no-checkout ${cmd_options}"
     echo_verbose "Compressing files..." 1
@@ -357,21 +358,10 @@ get() {
 }
 
 ######## MAIN ###########
-badf() {
-    return 0
-}
-#tar -czvf license.tar.gz ./LICENSE
-#TAR_ON && badf || die "ERROR: $0 line ${LINENO}, FUNCTION: ${FUNCNAME[0]}() Failed to tar, exiting"
-#exit
-#badf || [ ! $? ] || echo 'failed'
-#echo 'hello' || [ false ] && echo 'failed'
-#  echo $?
 
-#exit
 validate
 init
-
 get
-VERBOSE_ON && show_verbose
+show_verbose
 
 #show_errors
